name: toyota_accessory_app
description: Toyota accessory app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI Enhancements
  cupertino_icons: ^1.0.6
  nb_utils: ^7.0.4
  get: ^4.6.6
  google_fonts: ^6.2.1
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.9
  flutter_staggered_grid_view: ^0.7.0
  smooth_page_indicator: ^1.2.0+3
  animations: ^2.0.11
  lottie: ^3.1.2
  flutter_spinkit: ^5.2.1
  rive: ^0.13.15
  animated_text_kit: ^4.2.2
  motion_toast: ^2.0.0
  carousel_slider: ^5.0.0
  flutter_slidable: ^3.1.1
  flutter_neumorphic: ^3.2.0
  card_swiper: ^3.0.1
  dotted_border: ^2.0.0+2
  dotted_line: ^3.2.2
  shimmer: ^3.0.0
  flutter_native_splash: ^2.4.2

  # Navigation & Gestures
  go_router: ^14.3.0
  gesture_x_detector: ^1.1.0

  # State Management
  mobx: ^2.3.3+2
  flutter_mobx: ^2.2.1+1
  mobx_codegen: ^2.6.1
  build_runner: ^2.4.12

  # Network & API Management
  dio: ^5.4.0
  shared_preferences: ^2.3.2
  http: ^1.2.2
  connectivity_plus: ^6.1.0

  # Notifications
  firebase_messaging: ^15.1.3
  flutter_local_notifications: ^17.2.2

  # Forms & Inputs
  flutter_form_builder: ^9.5.0
  pin_code_fields: ^8.0.0
  flutter_colorpicker: ^1.1.0

  # Layout & Data Visuals
  responsive_framework: ^1.5.1
  syncfusion_flutter_charts: ^27.1.57
  syncfusion_flutter_datagrid: ^27.1.57

  # Miscellaneous
  photo_view: ^0.15.0
  video_player: ^2.9.1
  showcaseview: ^3.0.0
  confetti: ^0.8.0
  pull_to_refresh: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/toyota_logo.png
  # Optional configurations
  android_12:
    image: assets/images/toyota_logo.png
    color: "#FFFFFF"
  ios: true
  android: true
  web: false